from sqlalchemy import (
    JSON, Column, Integer, String, DateTime, ForeignKey, Float, Text
)
from sqlalchemy.orm import relationship
from app.db.base import Base
from datetime import datetime


class Explanation(Base):
    """
    Per-event SHAP explanation — the 'why' behind each detection.
 
    top_features     : [{"name": "failed_login_count", "shap": 0.43}, ...]
    counter_factuals : [{"change": "reduce failed_logins to <5", "outcome": "benign"}]
    narrative        : Human-readable explanation generated by the LLM.
                       e.g. "This event was classified as malicious primarily
                              because of 47 failed SSH attempts from 212.44.15.2
                              within 2 minutes, which is 8.3 standard deviations
                              above the baseline."
    """
    __tablename__ = "explanations"
 
    id              = Column(Integer, primary_key=True, index=True)
    analysis_id     = Column(Integer, ForeignKey("analyses.id"),      nullable=False)
    threat_event_id = Column(Integer, ForeignKey("threat_events.id"), nullable=True)
 
    feature_name    = Column(String(128), default="")   # top contributing feature
    shap_value      = Column(Float, nullable=True)      # SHAP value for that feature
    base_value      = Column(Float, nullable=True)      # model base / expected value
 
    top_features    = Column(JSON, nullable=True)       # list[{name, shap, direction}]
    counter_factuals= Column(JSON, nullable=True)       # list[{change, outcome}]
    narrative       = Column(Text, default="")          # LLM-generated explanation
 
    created_at      = Column(DateTime, default=datetime.utcnow)
 
    analysis     = relationship("Analysis",    back_populates="explanations")
    threat_event = relationship("ThreatEvent", back_populates="explanations")