from datetime import datetime
from sqlalchemy.orm import Session
from fastapi import HTTPException

from app.models.report import Report
from app.models.analysis import Analysis
from app.models.threat_event import ThreatEvent
from app.models.log_file import LogFile
from app.models.alert import Alert


def generate_report(db: Session, analysis_id: int, user_id: int) -> Report:
    analysis = db.query(Analysis).filter(Analysis.id == analysis_id).first()
    if not analysis:
        raise HTTPException(404, "Analysis not found")

    # check if report already exists for this analysis
    existing = db.query(Report).filter(
        Report.analysis_id == analysis_id
    ).first()
    if existing:
        return existing

    lf = db.query(LogFile).filter(LogFile.id == analysis.log_file_id).first()
    filename = lf.original_name if lf else "unknown"

    # count for case number
    report_count = db.query(Report).count() + 1
    case_number  = f"F-{str(report_count).zfill(3)}-ALPHA-{chr(64 + (report_count % 26) + 1)}"

    report = Report(
        analysis_id      = analysis_id,
        created_by       = user_id,
        title            = f"Forensic Incident Report: #XAI-{datetime.utcnow().year}-{str(report_count).zfill(3)}",
        case_number      = case_number,
        status           = "draft",
        hash_sha256      = f"sha256:{analysis_id:04x}{'a' * 28}{report_count:04x}",
        chain_of_custody = f"Generated by AI-Core 01 → Pending review",
        clearance_level  = 3,
        generated_at     = datetime.utcnow(),
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


def get_report_detail(db: Session, report_id: int) -> dict:
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(404, "Report not found")

    analysis = db.query(Analysis).filter(
        Analysis.id == report.analysis_id
    ).first()

    lf = db.query(LogFile).filter(
        LogFile.id == analysis.log_file_id
    ).first() if analysis else None

    # threat events → critical artifacts table
    threat_events = (
        db.query(ThreatEvent)
        .filter(ThreatEvent.analysis_id == report.analysis_id)
        .order_by(ThreatEvent.occurred_at.desc())
        .all()
    )

    artifacts = []
    for te in threat_events:
        artifacts.append({
            "timestamp": te.occurred_at.strftime("%Y-%m-%d  %H:%M:%S")
                         if te.occurred_at else "—",
            "source":    te.username or te.source_ip or "UNKNOWN",
            "action":    te.event_type,
            "status":    te.severity.upper(),
        })

    # threat vector distribution from shap_data
    shap_raw = analysis.shap_data or {} if analysis else {}
    total    = sum(shap_raw.values()) or 1
    vectors  = [
        {
            "label":      feat.replace("_", " ").title(),
            "percentage": round((val / total) * 100, 1),
        }
        for feat, val in sorted(
            shap_raw.items(), key=lambda x: x[1], reverse=True
        )
    ]
    # cap at 5 for the bar chart
    vectors = vectors[:5]
    # relabel as VEC_A, VEC_B etc to match your BarChart labels
    for i, v in enumerate(vectors):
        v["label"] = f"VEC_{chr(65+i)}"

    # metric card
    critical_alerts = db.query(Alert).filter(
        Alert.analysis_id == report.analysis_id,
        Alert.level       == "critical",
    ).count()

    metric_card = {
        "integrity_score":  round((1 - (analysis.threat_score or 0)) * 100, 1)
                            if analysis else 0.0,
        "total_artifacts":  len(threat_events),
        "alerts_critical":  critical_alerts,
        "processing_time":  analysis.duration_sec if analysis else 0.0,
        "case_number":      report.case_number,
        "hash_sha256":      f"SHA256: {report.hash_sha256}",
        "chain_of_custody": report.chain_of_custody,
    }

    return {
        "id":               report.id,
        "title":            report.title,
        "case_number":      report.case_number,
        "status":           report.status,
        "clearance_level":  report.clearance_level,
        "generated_at":     report.generated_at,
        "signed_at":        report.signed_at,
        "executive_summary": analysis.summary if analysis else "",
        "metric_card":      metric_card,
        "threat_vectors":   vectors,
        "critical_artifacts": artifacts,
    }


def list_reports(db: Session, user_id: int, see_all: bool) -> list[Report]:
    q = db.query(Report)
    if not see_all:
        q = q.filter(Report.created_by == user_id)
    return q.order_by(Report.generated_at.desc()).all()


def append_notes(db: Session, report_id: int, notes: str, user_id: int) -> Report:
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(404, "Report not found")
    if report.created_by != user_id:
        raise HTTPException(403, "Access denied")

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    existing  = report.chain_of_custody or ""
    report.chain_of_custody = f"{existing}\n[{timestamp}] {notes}".strip()
    db.commit()
    db.refresh(report)
    return report